export interface Dollar {
  name: string;
  ask: string;
  bid: string;
  arrow: string;
  ar_name: string;
  icon: string;
  change: string;
  change_percentage: string;
}

// [
//   {
//     name: "USD",
//     ask: "13200",
//     bid: "13700",
//     arrow: "1",
//     ar_name: "دولار أمريكي",
//     icon: "us.png",
//     change: "900",
//     change_percentage: "7.03",
//   },
//   {
//     name: "EUR",
//     ask: "13724",
//     bid: "14249",
//     arrow: "1",
//     ar_name: "يورو",
//     icon: "euro.png",
//     change: "913",
//     change_percentage: "6.85",
//   },
//   {
//     name: "TRY",
//     ask: "373",
//     bid: "389",
//     arrow: "1",
//     ar_name: "ليرة تركية",
//     icon: "tr.png",
//     change: "25",
//     change_percentage: "6.87",
//   },
//   {
//     name: "EGP",
//     ask: "257",
//     bid: "269",
//     arrow: "1",
//     ar_name: "جنيه مصري",
//     icon: "eg.png",
//     change: "18",
//     change_percentage: "7.17",
//   },
//   {
//     name: "SAR",
//     ask: "3517",
//     bid: "3654",
//     arrow: "1",
//     ar_name: "ريال سعودي",
//     icon: "sa.png",
//     change: "237",
//     change_percentage: "6.94",
//   },
//   {
//     name: "JOD",
//     ask: "18623",
//     bid: "19336",
//     arrow: "1",
//     ar_name: "دينار أردني",
//     icon: "jo.png",
//     change: "1263",
//     change_percentage: "6.99",
//   },
//   {
//     name: "AED",
//     ask: "3591",
//     bid: "3730",
//     arrow: "1",
//     ar_name: "درهم إماراتي",
//     icon: "ae.png",
//     change: "243",
//     change_percentage: "6.97",
//   },
//   {
//     name: "QAR",
//     ask: "3620",
//     bid: "3760",
//     arrow: "1",
//     ar_name: "ريال قطري",
//     icon: "qar.png",
//     change: "238",
//     change_percentage: "6.76",
//   },
//   {
//     name: "BHD",
//     ask: "35019",
//     bid: "36367",
//     arrow: "1",
//     ar_name: "دينار بحريني",
//     icon: "bh.png",
//     change: "2309",
//     change_percentage: "6.78",
//   },
//   {
//     name: "LYD",
//     ask: "2679",
//     bid: "2785",
//     arrow: "1",
//     ar_name: "دينار ليبي ",
//     icon: "libya.png",
//     change: "173",
//     change_percentage: "6.62",
//   },
//   {
//     name: "KWD",
//     ask: "42800",
//     bid: "44447",
//     arrow: "1",
//     ar_name: "دينار كويتي",
//     icon: "kw.png",
//     change: "2817",
//     change_percentage: "6.77",
//   },
//   {
//     name: "OMR",
//     ask: "34313",
//     bid: "35633",
//     arrow: "1",
//     ar_name: "ريال عماني",
//     icon: "omr.png",
//     change: "2253",
//     change_percentage: "6.75",
//   },
//   {
//     name: "GBP",
//     ask: "16529",
//     bid: "17166",
//     arrow: "1",
//     ar_name: "جنيه استرليني",
//     icon: "gb.png",
//     change: "1099",
//     change_percentage: "6.84",
//   },
//   {
//     name: "SEK",
//     ask: "1190",
//     bid: "1239",
//     arrow: "1",
//     ar_name: "كرون سويدي",
//     icon: "sweden.png",
//     change: "83",
//     change_percentage: "7.18",
//   },
//   {
//     name: "CAD",
//     ask: "9170",
//     bid: "9525",
//     arrow: "1",
//     ar_name: "دولار كندي",
//     icon: "cad.png",
//     change: "612",
//     change_percentage: "6.87",
//   },
//   {
//     name: "NOK",
//     ask: "1156",
//     bid: "1203",
//     arrow: "1",
//     ar_name: "كرون نرويجي",
//     icon: "nok.png",
//     change: "76",
//     change_percentage: "6.74",
//   },
//   {
//     name: "DKK",
//     ask: "1838",
//     bid: "1910",
//     arrow: "1",
//     ar_name: "كرون دينماركي",
//     icon: "dkk.png",
//     change: "123",
//     change_percentage: "6.88",
//   },
// ];
